frontend/controllers/RouteController.php
<?php

namespace frontend\controllers;

use Yii;
use app\models\RouteModel;
use common\models\TruckModel;
use common\models\RouteByTruckModel;
use app\models\SettingsModel;
use app\models\search\RouteSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\UploadCSVForm;
use yii\web\UploadedFile;
use yii\helpers\Json;
use yii\filters\AccessControl;
use yii\web\Request;
/**
 * RouteController implements the CRUD actions for RouteModel model.
 */
class RouteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index','suspected','geodata','helloworld'],
                'rules' => [
                    [
                        'actions' => ['index','suspected','geodata'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],                   
                ],
            ],        
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }
    public function actionIndex()
    {

        $searchModel = new RouteSearch();
        $searchModel->setAttributes([]); 
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $modelCSV = new UploadCSVForm();

        if (Yii::$app->request->isPost) {

            $modelCSV->load ( Yii::$app->request->post() );
            if( $modelCSV->validate() ){

                $dateQuery = explode( '/', $modelCSV->from_date );
                $dateQuery = $dateQuery[1].'/'.$dateQuery[0].'/'.$dateQuery[2] ;
                $arData = Yii::$app->parserGPS->parse( $truckName = $modelCSV->truck, $date = $dateQuery.'%2012:00:00%20AM' ); 
                
                if( is_array( $arData ) && $arData != null  ){

                    RouteModel::deleteAll('id>0');
                    Yii::$app->db->createCommand()->truncateTable( RouteModel::tableName() );

                    $truckModel = TruckModel::find()->where(['name' => $truckName])->one();
                    $truckId = $truckModel->id;
                    /*if( isset( $truckModel->id ) ){
                        $truckId = $truckModel->id;
                    }else{
                        $truckModel = new TruckModel();
                        $truckModel->name = $truckName;
                        if( $truckModel->save() ){
                            $truckId = $truckModel->id;
                        }
                    } */
                    
                    for ($row = 0; $row < count( $arData ) -1 ; $row++) {
                        $modelNewRoute = new RouteModel();
                        $modelNewRoute->truck_id  = $truckId;
                        $modelNewRoute->name_file = '11'; 
                        $modelNewRoute->date      = date('Y-m-d h:i:s A', strtotime( $arData[$row][2] ) ) ;
                        $modelNewRoute->status    = $arData[$row][3]; //comentario
                        $modelNewRoute->location  = $arData[$row][4]; //comentario
                        $modelNewRoute->battery   = $arData[$row][5]; //comentario
                        $modelNewRoute->lat_len   = $arData[$row][6]; //latitud
                        $modelNewRoute->speed     = $arData[$row][7]; //velocidad
                        $modelNewRoute->distance  = $arData[$row][8]; //distance
                        $modelNewRoute->save();
                    }
                }
            }
            /*
            $modelCSV->filecsv = UploadedFile::getInstance($modelCSV, 'filecsv');
            if ($modelCSV->filecsv ){ //&& $modelCSV->validate()) {   
                $originalName = $modelCSV->filecsv->name;
                $truckName = explode( '_', $originalName )[0];
                $fileName = explode('.', $originalName)[0];

                $file = UploadedFile::getInstance($modelCSV, 'filecsv');

                $truckModel = TruckModel::find( 'name="'.$truckName.'"' );
                if( isset($truckModel->id) ){
                    //print_r($truckModel);exit();
                    $truckId = $truckModel->id;
                }else{
                    $truckModel = new TruckModel();
                    $truckModel->name = $truckName;
                    if( $truckModel->save() ){
                        $truckId = $truckModel->id;
                    }
                }   
                RouteModel::deleteAll('id>0');
                Yii::$app->db->createCommand()->truncateTable( RouteModel::tableName() );
                $fp = fopen($file->tempName, 'r');
                if( $fp ){
                    $first_time = 0;
                    do{
                        if( $first_time  <=2 || !is_numeric( $line[0] ) ) {
                            $first_time++;
                            continue;
                        }
                        $modelNewRoute = new RouteModel();
                        
                        $modelNewRoute->truck_id  = $truckId;
                        $modelNewRoute->name_file = '11'; 
                        $modelNewRoute->lat_len   = $line[6]; //latitud
                        $modelNewRoute->date      = date('Y-m-d h:i:s A', strtotime( $line[2] ) ); //fecha
                        $modelNewRoute->speed     = $line[7]; //velocidad
                        $modelNewRoute->distance  = $line[8]; //distance
                        $modelNewRoute->battery   = $line[5]; //comentario
                        $modelNewRoute->location  = $line[4]; //comentario
                        $modelNewRoute->status    = $line[3]; //comentario
                        $modelNewRoute->save();

                    }while( ($line = fgetcsv($fp, 1000, ",")) != FALSE);

                }
            }
            */
        }

        $yesterdayDate = date('d/m/Y',strtotime("-1 days"));

        $modelSuspected = new RouteModel( ); 
        
        $truckTheName = '';
        $middlePointX = 0;
        $middlePointY = 0;
        $routeDate = '';
        $routesModel = RouteModel::find()->one();
        if( isset( $routesModel->id ) ){
            $idRoute =  $routesModel->truck_id;
            $truckTheName = TruckModel::find()->where(['id'=>$idRoute])->one()->name;

            $firstPoint = RouteModel::find()->limit(1)->one()->lat_len;
            $routeDate = date( 'd/m/Y' , strtotime( RouteModel::find()->limit(1)->one()->date ) );
            
            $firstPoint = explode( ',', $firstPoint );

            $sql='SELECT * FROM '.RouteModel::tableName().' ORDER BY id DESC limit 1';
            
            $lastPoint=RouteModel::findBySql($sql)->all()[0]['lat_len'];

            $lastPoint = explode( ',', $lastPoint );
            $middlePoint = Yii::$app->geodesica->middlePoint( $firstPoint[0], $firstPoint[1], $lastPoint[0], $lastPoint[1] );
            $middlePointX = explode( ',', $middlePoint )[0];
            $middlePointY = explode( ',', $middlePoint )[1];
        }

        return $this->render('index', [
            'searchModel'   => $searchModel,
            'model'         => $dataProvider,
            'modelCSV'      => $modelCSV,
            'truckName'     => $truckTheName,
            'middlePointX'  => $middlePointX,
            'middlePointY'  => $middlePointY,
            'yesterdayDate' => $yesterdayDate,
            'routeDate' => $routeDate,
        ]);
    }

    public function actionSuspected(){
        $byTruck = isset( $_GET['byTruck']) ? $_GET['byTruck'] : '';
        
       /* if( $byTruck == ''){
            $modelAll = RouteModel::find()->all();
        }else{*/
            $sql      ='SELECT * FROM '.RouteByTruckModel::tableName().' WHERE DATE(`date`) = CURDATE() ';
            $modelAll = RouteByTruckModel::findBySql($sql)->all();
            //$modelAll = json_decode(json_encode($modelAll), FALSE);
            //$modelAll = RouteByTruckModel::find()->where(['truck_id'=>$truck_id,'date'=>date('d/m/Y')])->all();
        //}
        $settingsModel = SettingsModel::find()->where(['id'=>'1'])->one();
        $stoppedDistance = $settingsModel->stopped_distance;
        $stoppedPings = $settingsModel->stopped_pings;
        $shutdownMinutes = $settingsModel->shutdown_minutes;
        $arrayLatLen = [];
        if( $modelAll ){
            $count = 0;
            $tmpLat = 0;
            $tmpLen = 0;
            $startDate = 0;
            $possibleSuspected = 0;
            foreach( $modelAll as $key){
                if( $count == 0){
                    $tmpLat    = explode( ',', $key->lat_len )[0];
                    $tmpLen    = explode( ',', $key->lat_len )[1];
                    $startDate = $key->date;
                }
                $truckId = $key->truck_id;
                $currentLat = explode( ',', $key->lat_len )[0];
                $currentLen = explode( ',', $key->lat_len )[1];
                $endDate   = $key->date ;
                if( $tmpLat !=  $currentLat && $tmpLen != $currentLen && $startDate != $endDate ){
                    $distance = Yii::$app->geodesica->distance( $tmpLat, $tmpLen, $currentLat, $currentLen) ;

                    /*$datetime1 = strtotime($startDate);
                    $datetime2 = strtotime($endDate);
                    $interval  = abs($datetime2 - $datetime1);
                    $minutes   = intval($interval/60);

                    $datetime1 = new \DateTime($startDate);
                    $datetime2 = new \DateTime($endDate);
                    $interval = $datetime1->diff($datetime2);
                    $minutes = $interval->format('%i');*/

                    $t1 = strtotime($startDate);
                    $t2 = strtotime($endDate);
                    $delta_T = ($t2 - $t1);
                    $minutes = round(((($delta_T % 604800) % 86400) % 3600) / 60); 

frontend/views/route/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\RouteModel */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="route-model-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name_file')->textInput(['maxlength' => 100]) ?>

    <?= $form->field($model, 'lat_len')->textInput(['maxlength' => 100]) ?>

    <?= $form->field($model, 'date')->textInput() ?>

    <?= $form->field($model, 'speed')->textInput() ?>

    <?= $form->field($model, 'distance')->textInput(['maxlength' => 100]) ?>

    <?= $form->field($model, 'battery')->textInput(['maxlength' => 100]) ?>

    <?= $form->field($model, 'location')->textInput(['maxlength' => 100]) ?>

    <?= $form->field($model, 'status')->textInput(['maxlength' => 45]) ?>

    <?= $form->field($model, 'truck_id')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/route/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\RouteSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="route-model-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name_file') ?>

    <?= $form->field($model, 'lat_len') ?>

    <?= $form->field($model, 'date') ?>

    <?= $form->field($model, 'speed') ?>

    <?php // echo $form->field($model, 'distance') ?>

    <?php // echo $form->field($model, 'battery') ?>

    <?php // echo $form->field($model, 'location') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'truck_id') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/route/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\RouteModel */

$this->title = Yii::t('app', 'Create {modelClass}', [
    'modelClass' => 'Route Model',
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Route Models'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="route-model-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/route/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ActiveForm;
use yii\jui\DatePicker;
use common\models\TruckModel;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\RouteSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
//= $form->field($modelCSV, 'from_date')->widget(\yii\jui\DatePicker::classname(), [
    //'language' => 'ru',
    //'dateFormat' => 'yyyy-MM-dd',
//]) 


/*
<?php $form = ActiveForm::begin([
    'id' => 'csv-form',
    'options' => ['class' => 'form-horizontal', 'enctype'=>'multipart/form-data'],
]) ?>

<?= $form->field($modelCSV, 'filecsv')->fileInput() ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Subir', ['class' => 'btn btn-primary']) ?>
        </div>
    </div>
<?php ActiveForm::end() ?>
*/
$this->title = Yii::t('models/Route', 'id');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="route-model-index">

    <h1><?= Html::encode($this->title) ?></h1>
<div class="row">
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    <div class="col-xs-6 col-sm-4">
        <?php $form = ActiveForm::begin([
            'id' => 'query-form',
            'options' => ['class' => 'form-horizontal', ],
        ]) ?>
        <?php $modelCSV->from_date=isset( $_GET['truck_id'] )? date('d/m/Y') : $yesterdayDate;?>
        <?= $form->field($modelCSV, 'from_date')->widget(DatePicker::classname(), [
            //'language' => 'ru',
            //'dateFormat' => 'yyyy-MM-dd',
        ]) ?>

        <?php
            if( isset( $_GET['truck_id'] ) ){
                $modelCSV->truck=TruckModel::find()->where(['id'=>$_GET['truck_id']])->one()->name;
            }else{
                $modelCSV->truck=  '';
            }
        ?>
        <?php $dataList=ArrayHelper::map(TruckModel::find()->asArray()->all(), 'name', 'name');?>
        <?=$form->field($modelCSV, 'truck')->dropDownList($dataList, 
                 ['prompt'=>'-Selecciona un camion-',]) ?>

            <div class="form-group">
                <div class="col-lg-offset-1 col-lg-11">
                    <?= Html::submitButton('Consultar', ['class' => 'btn btn-primary']) ?>
                </div>
            </div>
        <?php ActiveForm::end() ?>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-8">
        
        <div class="container-fluid" id="div-suspected">
            
        </div>
    </div>
</div>
<hr>


    <style>
      #map-canvas {
        height: 600px;
        width: 100%;
        padding: 0px;
        overflow: none;
      }
    </style>


<script src="http://maps.googleapis.com/maps/api/js?v=3&sensor=false"></script>
<script>
(function(window, undefined){

    divSuspected = document.getElementById('div-suspected');
    var map = '';
    function initialize() {
      var mapOptions = {
        zoom: 12,
        center: new google.maps.LatLng(<?= $middlePointX; ?>, <?= $middlePointY; ?>),
        mapTypeId: google.maps.MapTypeId.HYBRID
      };

      map = new google.maps.Map(document.getElementById('map-canvas'),
          mapOptions);
        var json = (function () { 
            var json = null; 
            $.ajax({ 
                'async': false, 
                'global': false, 
                'url': "/route/geodata", 
                'dataType': "json", 
                'success': function (data) {
                    json = data; 
                }
            });
            return json;
        })();

        if( json != null){

          var flightPlanCoordinates = [];
            for (var i = 0, length = json.length; i < length; i++) {
                var data = json[i];
                flightPlanCoordinates.push(new google.maps.LatLng(data.lat, data.len));
            }


          var flightPath = new google.maps.Polyline({
            path: flightPlanCoordinates,
            geodesic: false,
            strokeColor: '#00FF00',
            strokeOpacity: 1.0,
            strokeWeight: 2
          });

          flightPath.setMap(map);
       }else{
            document.getElementById('map-canvas').style.display = 'none';
       }
    

// Construct the circle for each value in citymap.
  // Note: We scale the area of the circle based on the population.
    var jsonSuspected = (function () { 
        var jsonSuspected = null; 
        $.ajax({ 
            'async': false, 
            'global': false, 
            'url': "/route/suspected", 
            'dataType': "json", 
            'success': function (data) {
                jsonSuspected = data; 
            }
        });
        return jsonSuspected;
    })();
    //var flightPlanCoordinatesSuspected = [];
    if( jsonSuspected != null){
        if( jsonSuspected.length > 0){
            pointWhitSuspected = '<div class="alert alert-danger" role="alert" id="pointsSospected"><h5><?=$truckName;?> <?=$routeDate;?></h5>Puntos con Sospecha<br>';
            for (var i = 0, length = jsonSuspected.length; i < length; i++) {
                var data = jsonSuspected[i];
                
                pointWhitSuspected += data.id+'.-<a onclick="centerMapToPont('+data.lat+','+data.len+')" href="#">'+data.lat+','+data.len+'</a><br>';
                //flightPlanCoordinatesSuspected.push(new google.maps.LatLng(data.lat, data.len));
                 var populationOptions = {
                  strokeColor: '#FF0000',
                  strokeOpacity: 0.8,
                  strokeWeight: 2,
                  fillColor: '#FF0000',
                  fillOpacity: 0,
                  map: map,
                  center: new google.maps.LatLng(data.lat, data.len),
                  radius: Math.sqrt(10) * 100
                };
                // Add the circle for this city to the map.
                cityCircle = new google.maps.Circle(populationOptions);
            }

            divSuspected.innerHTML = pointWhitSuspected+"</div>";

        }else{
            divSuspected.innerHTML ='<div class="alert alert-success" role="alert" id="pointsSospected"><?=$truckName;?> <?=$routeDate;?></h5> <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Sin sospecha</div>';
        }
    }
    // donde obtienes la latitud y longitud
    //  fromLatLngToPoint("31.054712,-110.898137");
    
    window.centerMapToPont = function(lat,len){
        var b = new google.maps.LatLng(lat,len);
        // map ya se encuentra definido y creado
        map.setZoom(16);
        // aqui es donde haces el centrado
        map.setCenter(b);
    }
    //centerMapToPont(31.054712,-110.898137);
    
    if(!isNaN( $("#uploadcsvform-truck").val().split("-")[1]) &&  $("#pointsSospected").find("h5").text().split("-")[1].split(" ")[0] != $("#uploadcsvform-truck").val().split("-")[1] ){
        $("#query-form").submit();
    }   
}
    google.maps.event.addDomListener(window, 'load', initialize);

})(window);

</script>

<div class="span10" id="map-canvas"></div>
<?php \yii\widgets\Pjax::begin(); ?>
    <?= GridView::widget([
        'dataProvider' => $model,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            //'name_file',
        [
                'header' => Yii::t('models/Route','lat_len'),
                'format' => 'raw',
                'value'=>  function($data){
                    return '<a target="_blank" href="http://maps.google.com/maps?q='.$data->lat_len.'&iwloc=A&hl=en&t=k&z=20">'.$data->lat_len.'</a>';
                },

            ],            
            'date',
            'speed',
            'distance',
            'battery',
            //'location',
            'status',
            //'truck_id',

        ],
    ]); ?>
<?php \yii\widgets\Pjax::end(); ?>
</div>

frontend/views/route/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\RouteModel */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Route Model',
]) . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Route Models'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="route-model-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/route/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\RouteModel */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Route Models'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="route-model-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name_file',
            'lat_len',
            'date',
            'speed',
            'distance',
            'battery',
            'location',
            'status',
            'truck_id',
        ],
    ]) ?>

</div>